---
title: "Immigration to Norway"
output: html_document
runtime: shiny
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, label = data}

library(rmeetupdemo)
library(rworkshop_package)

imm_data <- create_immigration_df()

# this is the difference
# although in this case it is very small this is
# the beginning of a basic design pattern to keep
# all data manipulation code separate from the visualisation
# a classic modular design imo
imm_growth <- add_growth_rates(imm_data)

```

Immigration to Norway by country - absolute values since 1970

```{r, echo = FALSE, message = FALSE, warning = FALSE, label = viz1}

library(ggvis)

imm_growth %>% 
  ggvis(~background, ~value) %>% 
  layer_boxplots()

```

Growth rates of immigration to Norway by background

```{r, echo = FALSE, message = FALSE, warning = FALSE, label = viz2}

imm_growth %>% 
  ggvis(~time, ~percentage_change, fill = ~factor(background)) %>% 
  layer_points()

```

The distribution of yearly immigration quantities

```{r, echo = FALSE, message = FALSE, warning = FALSE, label = viz3}

imm_growth[complete.cases(imm_growth$percentage_change),] %>%
  group_by(time) %>%
  summarise(total_immigration = sum(value)) %>%
  ggvis(~total_immigration) %>%
  layer_densities(adjust = input_slider(.1, 2, value = 1, step = .1, label = "Bandwidth adjustment"))

```
